baseURL: https://meleu.sh/
languageCode: pt-br
title: meleu.sh

###############################################################################
# PaperMod configs
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/
theme: "PaperMod"
# configs pendentes:
###############################################################################
# - post cover image:
#   - https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#post-cover-image
# - otimização para SEO:
#   - https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#enhanced-seo
###############################################################################

buildDrafts: false
buildFuture: false
enableEmoji: true

###############################################################################
# menu no canto superior direito das páginas
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#add-menu-to-site
# https://gohugo.io/content-management/menus/
###############################################################################
menu:
  main:
    - identifier: historico
      name: histórico
      url: /historico/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: busca
      name: busca
      url: /busca/
      weight: 30
    - identifier: sobre
      name: sobre
      url: /sobre/
      weight: 99
###############################################################################


params:
  description: "meleu.sh - Linha de comando e shell script. Foco no conteúdo e sem distrações"
  author: meleu
  defaultTheme: dark
  showShareButtons: true
  showReadingTime: true
  showToc: true
  tocOpen: false
  showCodeCopyButtons: true
  images:
    - "assets/meleush.png"

  #showBreadCrumbs: true

  # sugerir outros posts ao final
  # (não gostei do fato de ficar acima dos links de compartilhamento)
  #showPostNavLinks: true 


  # página inicial
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#home-info-mode
  #############################################################################
  homeInfoParams:
    title: meleu.sh
    content: Compartilhando conhecimento sobre linha de comando e shell script. Foco no conteúdo e sem distrações.

  socialIcons:
    - name: rss
      url: "index.xml"
    - name: twitter
      url: "https://twitter.com/meleushell"
    - name: github
      url: "https://github.com/meleu"
    - name: linkedin
      url: "https://www.linkedin.com/in/meleu/"
    - name: kofi
      url: "https://ko-fi.com/meleu"
  # TODO: adicionar link para o youtube, quanto tiver
  #############################################################################

  # link para edição
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#edit-link-for-posts
  # TODO: adicionar quando tiver definido o repositório no github
  #############################################################################
  #editPost:
  #  URL: "https://github.com/meleu/sh/content"
  #  text: "Sugerir mudanças neste artigo"
  #  appendFilePath: true
  #############################################################################

  # config de busca
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
  #############################################################################
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

# config de busca
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON

