baseURL: https://meleu.sh/
languageCode: pt
defaultContentLanguage: pt
title: meleu.sh

# Eu tentei ser um site bilíngue, mas o esforço necessária iria tomar muito
# do meu tempo. Caso eu mude de ideia, esse commit vai ser útil:
# cd6ccd3b147500ff3810351d3708844d8c380db2

###############################################################################
# PaperMod configs
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/
# configs pendentes:
###############################################################################
# - post cover image:
#   - https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#post-cover-image
# - otimização para SEO:
#   - https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#enhanced-seo
###############################################################################
theme: "PaperMod"

buildDrafts: false
buildFuture: false
enableEmoji: true

# todos os arquivos em 'content/posts/' serão servidos na raiz
permalinks:
  posts: /:filename

# servindo o diretório 'img/' como 'static/img/'
# só acertei essa config vendo os exemplos desse artigo aqui:
# https://geeksocket.in/posts/hugo-modules/
module:
  mounts:
    - source: img/
      target: static/img/

###############################################################################
# menu no canto superior direito das páginas
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#add-menu-to-site
# https://gohugo.io/content-management/menus/
###############################################################################
menu:
  main:
    - identifier: historico
      name: histórico
      url: /historico/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: busca
      name: busca
      url: /busca/
      weight: 30
    - identifier: about
      name: sobre
      url: /sobre/
      weight: 99
###############################################################################

params:
  env: production
  description: >
    meleu.sh - Linha de comando e shell script. Foco no conteúdo e sem distrações.
  author: meleu
  images:
    - img/por-que-shell.gif
  assets:
    favicon: "/favicon.ico"
  defaultTheme: dark
  showShareButtons: true
  showReadingTime: true
  showToc: true
  tocOpen: false
  showCodeCopyButtons: true
  showBreadCrumbs: true

  # sugerir outros posts ao final
  # (não gostei do fato de ficar acima dos links de compartilhamento)
  #showPostNavLinks: true

  # página inicial
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#home-info-mode
  #############################################################################
  homeInfoParams:
    title: meleu.sh
    content: |
      Compartilhando conhecimento sobre linha de comando e shell script.

      Foco no conteúdo e sem distrações.

      > **Se você é iniciante em shell script [comece por aqui](/comeco)**.

  socialIcons:
    - name: other
      title: Link to my digital garden
      url: "index.xml"
    - name: github
      url: "https://github.com/meleu"
    - name: twitter
      url: "https://twitter.com/meleushell"
    - name: rss
      url: "index.xml"
  # TODO: adicionar link para o youtube, quanto tiver
  #############################################################################

  # google analytics
  # analytics:
  #   google:
  #     SiteVerificationTag: "UA-155045503-1"

  # link para edição
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#edit-link-for-posts
  #############################################################################
  editPost:
    URL: "https://github.com/meleu/meleudotsh/edit/master/content"
    text: "✏️ Edite este artigo"
    appendFilePath: true
  #############################################################################

  # config de busca
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
  #############################################################################
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

  # habilitando comentários:
  #############################################################################
  giscus:
    repo: "meleu/meleudotsh"
    repoId: "R_kgDOG_9USg"
    category: "Announcements"
    categoryId: "DIC_kwDOG_9USs4ChHrL"
    mapping: "pathname"
    strict: "0"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "bottom"
    theme: "preferred_color_scheme"
    lang: "pt"
    loading: "lazy"

# config de busca
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
outputs:
home:
  - HTML
  - RSS
  - JSON
